### ISSUE TITLE
Throws 'options != null': is not true

### ISSUE THREAD

**Issue by icodelifee** [invertase/flutterfire_desktop#19]
On launch, app throws the following error:
` Unhandled Exception: 'package:firebase_core_desktop/firebase_core_desktop.dart': Failed assertion: line 35 pos 12: 'options != null': is not true.`

Which I think is called due to FirebaseApp initialization in main(), the app is set up for web as well as macOS.
FirebaseConfigs for the different projects are intialized later.
![image](https://user-images.githubusercontent.com/18023153/141935989-74f19a2f-67f5-4a67-a478-d9ce82bf72c9.png)

**Comment by pr-Mais** [comment]
[A section is added to README](https://github.com/invertase/flutterfire_desktop#firebase-app-initialization) to clarify this part, thanks for reporting the issue!
