### ISSUE TITLE
Firebase realtime database or Firestore needs to be added

### ISSUE THREAD

**Issue by topperspal** [invertase/flutterfire_desktop#37]
Please add **Realtime Database** or **Firestore** so that we can start testing and using it.

**Comment by Ehesp** [comment]
Planned!

**Comment by richard457** [comment]
I would add FCM too since the notification is the core in many ways.

**Comment by worldwidee** [comment]
there are no updates for a while on projects. i wonder can we use firebase in 2022. Could you give any information about that?🙏

**Comment by lzzy12** [comment]
> there are no updates for a while on projects. i wonder can we use firebase in 2022. Could you give any information about that?🙏

was wondering the same. By when (or can we) we expect at least basic products like firestore implemented?

**Comment by Ehesp** [comment]
We don't have a time line yet since we're still focusing on getting auth stable. Once we have more information we'll provide an update.

**Comment by pr-Mais** [comment]
This is the current roadmap https://github.com/invertase/flutterfire_desktop/issues/52

**Comment by cbenhagen** [comment]
@pr-Mais As Firestore and realtime database are not on the roadmap for 2022, maybe this issue could be left open so we can get notified if anything changes?

**Comment by topperspal** [comment]
Why did you close it. I think closed issue means either you have resolved the issue or rejected completely. What do you mean?

**Comment by pr-Mais** [comment]
Discussions regarding any plans are moved over to #52, please feel free to start the discussion again regarding any packages you're waiting for.
