### ISSUE TITLE
DefaultFirebaseOptions are not supported for this platform

### ISSUE THREAD

**Issue by barbalex** [invertase/flutterfire_desktop#41]
After running into https://github.com/invertase/flutterfire_desktop/issues/19 and having to install the cli, create firebase_options.dart and add `options: DefaultFirebaseOptions.currentPlatform` when initializing the firebase App, I now run into this error:

```
Exception has occurred.
UnsupportedError (Unsupported operation: DefaultFirebaseOptions are not supported for this platform.)
```

Could this have something to do with the fact that windows can't be added as a platform on https://console.firebase.google.com?
<img width="567" alt="2022-01-06_18h34_06" src="https://user-images.githubusercontent.com/669783/148425701-d7079be7-7da5-4fd9-9136-4963009526f6.png">

**Comment by pr-Mais** [comment]
Windows and Linux aren't supported in Firebase Console.
Currently since the desktop packages under the hood use Identity Platform REST API, Web configurations can be used, but considering the CLI seems to be reading the current platform so it throws this exception.

@Salakar this is interesting case to think about for FF desktop

**Comment by Salakar** [comment]
Yep the current recommendation is to select web as a platform to generate the DefaultFirebaseOptions for, and then instead of `DefaultFirebaseOptions.currentPlatform` you can use `DefaultFirebaseOptions.web`

**Comment by barbalex** [comment]
@Salakar works. Thanks a lot!

**Comment by barbalex** [comment]
Or even more flexible:
```dart
bool needsWeb = Platform.isLinux | Platform.isWindows;
await Firebase.initializeApp(
  options: needsWeb
      ? DefaultFirebaseOptions.web
      : DefaultFirebaseOptions.currentPlatform,
);
```

**Comment by pr-Mais** [comment]
Just to clarify, macOS is included, as mentioned [in the README](https://github.com/invertase/flutterfire_desktop#readme)
> the plugin will override macOS implementation as it's currently being used for development purposes.

**Comment by romantitov** [comment]
> Yep the current recommendation is to select web as a platform to generate the DefaultFirebaseOptions for, and then instead of `DefaultFirebaseOptions.currentPlatform` you can use `DefaultFirebaseOptions.web`

I have the exception `PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))` 

when I run my app on windows with following configurations:

```
 await Firebase.initializeApp(
    options: DefaultFirebaseOptions.web,
  );
```

**Comment by szho42** [comment]
Hi, all, tried the solutions mentioned in this solution, but it does not work for flutter apps (for linux) with flutter version (3.10.6 - stable),  firebase_core (2.15.0) and cloud_firestore (4.8.4). 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:210)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43)
<asynchronous suspension>

Just wondering any timeline to officially support this for Linux/Windows?

Cheers

**Comment by ghost** [comment]
Have you taken a look at this package? 

https://pub.dev/packages/firebase_core_desktop

**Comment by szho42** [comment]
I tried with firebase_core_desktop, the UI can be displayed on Linux, however, it failed to fetch data from firestore. the function snapshots() won't be able to be called. See the message below:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method Query#snapshots on channel plugins.flutter.io/firebase_firestore)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelQuery.snapshots.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:150:28)
<asynchronous suspension>

**Comment by hitchcliff** [comment]
> Hi, all, tried the solutions mentioned in this solution, but it does not work for flutter apps (for linux) with flutter version (3.10.6 - stable), firebase_core (2.15.0) and cloud_firestore (4.8.4).
> 
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null) #0 FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:210) [#1](https://github.com/FirebaseExtended/flutterfire_desktop/pull/1) MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29) [#2](https://github.com/FirebaseExtended/flutterfire_desktop/pull/2) MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73) [#3](https://github.com/FirebaseExtended/flutterfire_desktop/pull/3) Firebase.initializeApp (package:firebase_core/src/firebase.dart:43)
> 
> Just wondering any timeline to officially support this for Linux/Windows?
> 
> Cheers

we got same issue.
