### ISSUE TITLE
MissingPluginException - Not able to reach Firestore.

### ISSUE THREAD

**Issue by al4nnw** [invertase/flutterfire_desktop#44]
I was trying to build a windows version of my project following <a href="https://firebase.flutter.dev/docs/overview/">this<a/> guide to initialize Firebase. But when I try to get a document from Firestore, I get the following error message:

> MissingPluginException (MissingPluginException(No implementation found for method DocumentReference#get on channel plugins.flutter.io/firebase_firestore))

I've tried:

- `flutter clean` then `flutter pub get`.
- Using `DefaultFirebaseOptions.web` instead of `DefaultFirebaseOptions.currentPlatform`.

**Firebase dependencies in pubspec.yaml**

-   firebase_core: "^1.9.0"

-   firebase_core_desktop: ^0.1.1-dev.0

-   firebase_auth: ^3.1.5

-   firebase_auth_desktop: ^0.1.1-dev.0

-   cloud_firestore: ^3.1.7

**flutter doctor -v**
<details>
<div class="snippet-clipboard-content position-relative overflow-auto">
<pre>
<code>
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.19042.1466], locale pt-BR)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
  
  [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
      • Android SDK at C:\Users\Alan\AppData\Local\Android\sdk
      • Platform android-31, build-tools 30.0.3
      • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
      • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
      • All Android licenses accepted.
  
  [√] Chrome - develop for the web
      • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
  
  [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
      • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
      • Visual Studio Community 2019 version 16.8.31005.135
      • Windows 10 SDK version 10.0.18362.0
  
  [√] Android Studio (version 4.2)
      • Android Studio at C:\Program Files\Android\Android Studio
      • Flutter plugin can be installed from:
         https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
         https://plugins.jetbrains.com/plugin/6351-dart
      • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
  
  [√] VS Code (version 1.63.2)
      • VS Code at C:\Users\Alan\AppData\Local\Programs\Microsoft VS Code
      • Flutter extension version 3.32.0
  
  [√] Connected device (3 available)
      • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1466]       
      • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
      • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.69
<code/>
<pre/>
<div/>
<details/>

**Comment by pr-Mais** [comment]
Firestore isn't yet supported, only Auth and Functions.
