### ISSUE TITLE
Auto close window after autentication flow

### ISSUE THREAD

**Issue by filipenanclarez** [invertase/flutterfire_desktop#47]
When authentication flows end, this screen is showed:

![image](https://user-images.githubusercontent.com/27212546/154818473-4af3f7bd-6e0c-4005-a6f8-9390982819ae.png)

Anyway to auto close this page or add a link to auto back to app?

**Comment by pr-Mais** [comment]
WebView will be supported soon on Windows similar to Linux & macOS instead of going to the browser for verification, this is just a temporary behavior.

**Comment by pr-Mais** [comment]
A new version with support for WebViews on Windows is out, with auto close after authentication flow is done, try it out.
