### ISSUE TITLE
Apple auth

### ISSUE THREAD

**Issue by filipenanclarez** [invertase/flutterfire_desktop#49]
Apple auth already done? 

If yes, can you provide a example of how implement?

**Comment by pr-Mais** [comment]
Apple isn't yet supported

**Comment by Ev1lT3rm1nal** [comment]
> Apple isn't yet supported

But will it be?

**Comment by pr-Mais** [comment]
Yes, it will be supported very soon.

**Comment by filipenanclarez** [comment]
You implementation not works on windows, só i think this issue must keep open.

We need apple auth in windows, linux and macos, #65 only fix the macOS needs.
