### ISSUE TITLE
phone authentication not working

### ISSUE THREAD

**Issue by vishwajit76** [invertase/flutterfire_desktop#53]
After enter mobile number, blank windows opened and throw below exception.

`Unhandled Exception: [firebase_auth/verification-canceled] Recaptcha verification process was canceled by user.`

**Comment by pr-Mais** [comment]
Could you provide minimal reproducible code?
What platform are you running on?
Did you try the example app first? Still same issue?

**Comment by vishwajit76** [comment]
I tested on windows 10 platform,

`ConfirmationResult? confirmationResult = await authController.getAuth.signInWithPhoneNumber(
      "+91" + mobileNumberController.text,
    );`

**Comment by vishwajit76** [comment]
![image](https://user-images.githubusercontent.com/25575802/157618483-c90cee95-de1c-44e6-b426-9e0fede9011c.png)

**Comment by pr-Mais** [comment]
Can you please try running the example app? let me know if the same problem appears there.

**Comment by vishwajit76** [comment]
same problem in example app
![image](https://user-images.githubusercontent.com/25575802/157656094-2c1a65e5-c607-4d26-96aa-35f896018e4d.png)

**Comment by pr-Mais** [comment]
Do you have the latest version of Microsoft Edge?
Check by opening `Edge > Settings > About Microsoft Edge`

![Screen Shot 2022-03-10 at 3 47 34 PM](https://user-images.githubusercontent.com/41123719/157664809-5f84517f-4df8-4864-a87c-b362f15abc3b.png)

**Comment by vishwajit76** [comment]
![image](https://user-images.githubusercontent.com/25575802/157669073-93e86530-552b-4102-bfe6-df3e24662014.png)

**Comment by pr-Mais** [comment]
My assumption is that it's not connecting to a localhost server which is why the returned token is `null` causing this error to throw.

See [here](https://github.com/invertase/flutterfire_desktop/blob/5f3606c3bcd474c4ea7f0d0cf3f040ad6511eadd/packages/firebase_auth/firebase_auth_dart/lib/src/api/authentication/phone.dart#L153-L157), can you put a breakpoint over [this line](https://github.com/invertase/flutterfire_desktop/blob/7f2aeb9bdf269456e3d551fe2a8417065845c3b3/packages/firebase_auth/firebase_auth_desktop/lib/src/internal/recaptcha_verifier_delegate.dart#L24) and tell me if it's returning a result or not?

**Comment by pr-Mais** [comment]
Could you try running the Dart CLI example by running this following from the root of `flutterfire_desktop`:
```
dart run packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart login
```
This should prompt you to enter a phone number, then will take you to the default browser for reCAPTCHA verification, which also runs on localhost, this will tell us if there's an issue with the localhost server on your machine.

**Comment by vishwajit76** [comment]
got this error

D:\flutterfire_desktop-main>dart run packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart login
Error: Couldn't resolve the package 'ansicolor' in 'package:ansicolor/ansicolor.dart'.
Error: Couldn't resolve the package 'args' in 'package:args/args.dart'.
Error: Couldn't resolve the package 'cli_util' in 'package:cli_util/cli_logging.dart'.
Error: Couldn't resolve the package 'firebase_auth_dart' in 'package:firebase_auth_dart/firebase_auth_dart.dart'.
Error: Couldn't resolve the package 'firebase_core_dart' in 'package:firebase_core_dart/firebase_core_dart.dart'.
packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart:7:8: Error: Not found: 'package:ansicolor/ansicolor.dart'
import 'package:ansicolor/ansicolor.dart';
       ^
packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart:8:8: Error: Not found: 'package:args/args.dart'
import 'package:args/args.dart';
       ^
packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart:9:8: Error: Not found: 'package:cli_util/cli_logging.dart'
import 'package:cli_util/cli_logging.dart';
       ^
packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart:10:8: Error: Not found: 'package:firebase_auth_dart/firebase_auth_dart.dart'
import 'package:firebase_auth_dart/firebase_auth_dart.dart';
       ^
packages/firebase_auth/firebase_auth_dart/example/bin/firebase_auth_dart_example.dart:11:8: Error: Not found: 'package:firebase_core_dart/firebase_core_dart.dart'
import 'package:firebase_core_dart/firebase_core_dart.dart';
       ^

**Comment by pr-Mais** [comment]
run `dart pub get` in `packages/firebase_auth/firebase_auth_dart/example`

**Comment by vishwajit76** [comment]
Using cli successfully open webpage in browser. But at run time error was occured.

D:\flutterfire_desktop-main\packages\firebase_auth\firebase_auth_dart\example>dart run bin/firebase_auth_dart_example.dart login
Please login/register to continue
Email/Phone: +91823839XXXX
Attempting to sign in with phone number +91823839XXXX...

SMS Code: 777316
Signed in successfully! �

**Comment by pr-Mais** [comment]
I'm not sure, since I'm unable to reproduce I cannot know where's the exact issue

**Comment by worldwidee** [comment]
same problem here

**Comment by worldwidee** [comment]
also it is happening with example project. By the way  i updated my edge before that.  White screen is opening instead of rechaptcha screen

**Comment by vishwajit76** [comment]
any update?

**Comment by vishwajit76** [comment]
example project is working now but in my case after enter opt it show me firebase error

Unhandled Exception: [firebase_auth/invalid-auth] This user's credential isn't valid for this project. This can happen if the user's token has been tampered with, or if the user isn't for the project associated with this API key.

I used web app firebase configuration.

**Comment by pr-Mais** [comment]
This happens when the token of the user is invalid, the good news is that it seems ReCaptcha issue is solved now. Make sure to clean any caches, and run `flutter clean`. 

I have 2 questions:
- The error happened in the example app in `firebase_auth_desktop`? if not, could you pleaser clone a fresh copy from the repo and run it (it already has Firebase configurations).
- Are you sure that the configurations you used are up-to-date and a fresh copy from a valid Firebase project?

**Comment by vishwajit76** [comment]
After auth signOut it's working.
