### ISSUE TITLE
firebase_auth/captcha-check-failed

### ISSUE THREAD

**Issue by TarekFaysal** [invertase/flutterfire_desktop#58]
`signInWithPhoneNumber` method works fine for web platform. 
`signInWithPhoneNumber` method for desktop (macos, windows) only works with test phone number and verification code.
![test phone number](https://user-images.githubusercontent.com/44679938/160765776-62bbcb0e-cc36-4d5a-b58d-bb9312efb353.PNG)
But it does not work with any real phone numbers. This error shows up when any real phone number is provided.

> [firebase_auth/captcha-check-failed] The reCAPTCHA response token was invalid, expired, or is called from a non-whitelisted domain.

How can I solve this issue?

**Comment by pr-Mais** [comment]
Go to `Authentication > Sign-in method > Authorized domains`, then add `127.0.0.1` to the list of authorized domains in Firebase Console.

**Comment by TarekFaysal** [comment]
Thanks for the reply. It works as intended.
