### ISSUE TITLE
🐛 [auth] Apple Auth

### ISSUE THREAD

**Issue by filipenanclarez** [invertase/flutterfire_desktop#68]
As i said in #49, the partial solution implemented in #65 not fix the main problem.

We need oAuth Apple Auth work in all platforms, not only in macOS. I think some changes in desktop_webview_auth is needed to make this works.

**Comment by pr-Mais** [comment]
The way OAuth providers work with FlutterFire is through a **third-party plugin**. 

For example, Google is added on mobile and web using [sign_in_with_google](https://pub.dev/packages/google_sign_in) plugin, we created [desktop_webview_auth](https://pub.dev/packages/desktop_webview_auth) to handle sign in with Google on Desktop platforms, but in both cases `firebase_auth` doesn't have this support built-in. 

Similarly for Apple Auth, if the plugin [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple) would add support for Windows or Linux, then you can easily get the credentials and use them in firebase_auth through `signInWithCredentials` method. 

Therefore, it's not within the current scope of Firebase Auth or FlutterFire Desktop.

**Comment by filipenanclarez** [comment]
> The way OAuth providers work with FlutterFire is through a **third-party plugin**.
> 
> For example, Google is added on mobile and web using [sign_in_with_google](https://pub.dev/packages/google_sign_in) plugin, we created [desktop_webview_auth](https://pub.dev/packages/desktop_webview_auth) to handle sign in with Google on Desktop platforms, but in both cases `firebase_auth` doesn't have this support built-in.
> 
> Similarly for Apple Auth, if the plugin [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple) would add support for Windows or Linux, then you can easily get the credentials and use them in firebase_auth through `signInWithCredentials` method.
> 
> Therefore, it's not within the current scope of Firebase Auth or FlutterFire Desktop.

I understand, but finally, we can't got the solution at all. My user cannot use one account in iPhone and then, on windows, use another account. So a simple `if platform == macos then show apple button` not resolve this problem at the and. 

I think the desktop_webview_auth is the right way to handle this. So i open an issue there. 

Thank you for explanation.
