### ISSUE TITLE
[📚] The Firebase docs should mention Windows and Linux

### ISSUE THREAD

**Issue by feinstein** [invertase/flutterfire_desktop#84]
Currently the Firebase documentation shows this table:

![image](https://user-images.githubusercontent.com/8120472/173915599-61aef384-2d4b-40e2-b977-9338bce530d4.png)

On the last column there's just "Other Mac", but it makes no mention to Windows and Linux. I think it should be called "Other platforms".

**Comment by pr-Mais** [comment]
This project is a community effort sponsored by Invertase, and the docs now are official, so it can't be included there.
